### ISSUE TITLE
Bytes payload

### ISSUE THREAD

**Issue by trollfot** [calcite/zmq_tubes#14]
Hello,
Thank you very much for this very easy to use and nicely coded package.

I'm trying to send bytes in a REQ/REP scenario, but it's failing due to  this line : https://github.com/calcite/zmq_tubes/blob/master/zmq_tubes/manager.py#L116

I'm wondering if i'm missing something obvious or if only the topic should be decoded ?

**Comment by BlackSmith** [comment]
Hello @trollfot ,
sorry for my slow reaction.  
Generally I assumed that the payload is simple string. However, you are right, bytes or binary data is good idea.
I will try to do it in next version.
